name: Demo Workflow

on: 
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message 
        run: echo "Welcome to the Test Automation Workflow"
