# This wWrkflow excutes he automated test cases in the repo 

name: Run Tests

on:
  # Trigger1: trigger [run-tests] is sent from the website main repo when pushing new commit
  repository_dispatch: 
    types: [run-tests]

  # Trigger2: when pushing new code to the tests repo
  push:
    branches:
      - main
    paths:
      - "src/**"

  # Trigger3: Manual Trigger 
  workflow_dispatch:

# allow the workflow to commit code to the repo
permissions:
  contents: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Debug - Find testng.xml
        run: |
          echo "Looking for testng.xml:"
          find . -name "testng.xml" -type f
          echo "Current directory contents:"
          ls -la

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Changed from 11 to 21
          distribution: 'temurin'
          
      - name: Run tests
        run: mvn clean test -B --no-transfer-progress -Dheadless=true #cmd prompt to run tests

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add test-output || true
          git commit -m "chore: update test results [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
          
#      - name: Sync test-output to TestReport repository
#        env:
#          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
#        run: |
#          git clone https://x-access-token:$PAT@github.com/MahmoudFawzyAOE2/mft1998-portfolio-TestReport.git temp-repo2
#          cd temp-repo2
#
#          git config user.name "github-actions[bot]"
#          git config user.email "github-actions[bot]@users.noreply.github.com"
#
#          rm -rf test-output
#          cp -r ../test-output ./
#
#          git add test-output/
#          git commit -m "Update test-output from repo1 CI/CD [skip ci]" || exit 0
#          git push origin main
#
#          cd ..
#          rm -rf temp-repo2

      - name: Send Email with Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Portfolio Website Tests Results"
          to: 1998mft1998@gmail.com
          from: GitHub Actions
          body: "Tests finished. Check results in GitHub Actions artifacts or at https://mahmoudfawzyaoe2.github.io/mft1998-portfolio-TestReport."
