name: Run Tests

on:
  repository_dispatch: #Run this workflow only when the trigger [run-tests] is sent
    types: [run-tests]
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: MahmoudFawzyAOE2/mft1998-portfolio
          token: ${{ secrets.PAT_TOKEN }}

      - name: Checkout test repo
        uses: actions/checkout@v4

      - name: Debug - Find testng.xml
        run: |
          echo "Looking for testng.xml:"
          find . -name "testng.xml" -type f
          echo "Current directory contents:"
          ls -la


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Changed from 11 to 21
          distribution: 'temurin'
          
      - name: Run tests
        run: mvn test -B -DsuiteXmlFile=TestNG.xml #cmd prompt to run tests

      - name: Send Email with Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Portfolio Website Tests Results"
          to: 1998mft1998@gmail.com
          from: GitHub Actions
          body: "Tests finished. Check results in GitHub Actions artifacts."
