# This wWrkflow excutes he automated test cases in the repo 

name: Run Tests

on:
  # Trigger1: trigger [run-tests] is sent from the website main repo when pushing new commit
  repository_dispatch: 
    types: [run-tests]

  # Trigger2: when pushing new code to the tests repo
  push:
    branches:
      - main
    paths:
      - "src/**"

  # Trigger3: Manual Trigger 
  workflow_dispatch:

# allow the workflow to commit code to the repo
permissions:
  contents: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'  # Changed from 11 to 21
          distribution: 'temurin'
          
      - name: Run tests
        run: mvn clean test -B --no-transfer-progress -Dheadless=true #cmd prompt to run tests
        continue-on-error: true
      
      - name: List Allure results
        run: |
          ls -R target/allure-results || echo "No allure results found in target"  
          ls -R /allure-results || echo "No allure results found in root"  
        
      - name: Load test report history
        uses: actions/checkout@v5.0.0
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
