name: Run Tests

on:
  repository_dispatch: #Run this workflow only when the trigger [run-tests] is sent
    types: [run-tests]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repo
        uses: actions/checkout@v4

      - name: Checkout website repo
        uses: actions/checkout@v4
        with:
          repository: MahmoudFawzyAOE2/mft1998-portfolio
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: mvn test #cmd prompt to run tests

      - name: Send Email with Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Portfolio Website Tests Results"
          to: 1998mft1998@gmail.com
          from: GitHub Actions
          body: "Tests finished. Check results in GitHub Actions artifacts."
