on:
    deployment_status:
      types: [completed]
      branches: 
        - gh-pages

jobs:
  send-email: 
    runs-on: ubuntu-latest 
    steps:
      - name: Send Email with Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Portfolio Website Tests Results"
          to: 1998mft1998@gmail.com
          from: GitHub Actions
          body: "Tests finished. Check results in GitHub Actions artifacts or at https://mahmoudfawzyaoe2.github.io/mft1998-portfolio-TestAutomation"
