name: After Pages Deployment

on:
  deployment_status:
    types: [success]

jobs:
  after-pages:
    if: github.event.deployment_status.environment == 'github-pages' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Confirm Pages deployed
        run: echo "✅ GitHub Pages has been deployed successfully!"

      - name: Send Email with Results
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Portfolio Website Tests Results"
          to: 1998mft1998@gmail.com
          from: GitHub Actions
          body: "Tests finished. Check results in GitHub Actions artifacts or at https://mahmoudfawzyaoe2.github.io/mft1998-portfolio-TestAutomation"
